/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logica.Abeja;

/**
 *
 * @author lalem
 */
public class InfoAbeja extends javax.swing.JFrame {

    /**
     * Creates new form InfoAbeja
     */
    public InfoAbeja(Abeja abeja) {
        initComponents();
        if(abeja.getAncestros() == null){
            bTAncestro1.setEnabled(false);
            bTAncestro2.setEnabled(false);
        }
        String color = "n";
        switch(abeja.getColorFav()){
                case 0:
                    color = "Rojo";
                    break;
                case 1:
                    color = "Verde";
                    break;
                case 2:
                    color = "Azul";
                    break;
                case 3:
                    color = "Amarillo";
                    break;
                case 4:
                    color = "Morado";
                    break;
                case 5:
                    color = "Celeste";
                    break;
                case 6:
                    color = "Naranja";
                    break;
                case 7:
                    color = "Rosa";
                    break;
            }
        colorFav.setText(color);
        String orden = "";
        switch (abeja.getOrden()){
            case 0:
                orden = "profundidad";
            case 1:
                orden = "Anchura";
            case 2:
                orden = "Random";
        }
        OrdBusq.setText(orden);
        dirFav.setText(abeja.getDireccionFav().name());
        distMax.setText(Integer.toString(abeja.getDistMax()));
        gen.setText(Integer.toString(abeja.getGeneracion()));
        adn.setText(abeja.getADN());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bTAncestro1 = new javax.swing.JButton();
        bTAncestro2 = new javax.swing.JButton();
        colorFav = new javax.swing.JTextField();
        dirFav = new javax.swing.JTextField();
        OrdBusq = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        distMax = new javax.swing.JTextField();
        adn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Abeja");

        jLabel2.setText("Color Favorito");

        jLabel3.setText("Dirección Favorita");

        jLabel4.setText("Orden de busqueda");

        jLabel5.setText("Generación");

        jLabel6.setText("DistanciaMáxima");

        jLabel7.setText("Secuencia ADN");

        bTAncestro1.setText("Ancestro 1");
        bTAncestro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTAncestro1ActionPerformed(evt);
            }
        });

        bTAncestro2.setText("Ancestro 2");

        colorFav.setEditable(false);
        colorFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorFavActionPerformed(evt);
            }
        });

        dirFav.setEditable(false);

        OrdBusq.setEditable(false);

        gen.setEditable(false);
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });

        distMax.setEditable(false);

        adn.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTAncestro1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bTAncestro2)
                    .addComponent(colorFav)
                    .addComponent(dirFav)
                    .addComponent(OrdBusq)
                    .addComponent(gen)
                    .addComponent(distMax)
                    .addComponent(adn, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(colorFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dirFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(OrdBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(adn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTAncestro1)
                    .addComponent(bTAncestro2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTAncestro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTAncestro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTAncestro1ActionPerformed

    private void colorFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFavActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrdBusq;
    private javax.swing.JTextField adn;
    private javax.swing.JButton bTAncestro1;
    private javax.swing.JButton bTAncestro2;
    private javax.swing.JTextField colorFav;
    private javax.swing.JTextField dirFav;
    private javax.swing.JTextField distMax;
    private javax.swing.JTextField gen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
