/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;
import logica.Abeja;

/**
 *
 * @author lalem
 */
public class InfoAbeja extends javax.swing.JFrame {

    /**
     * Creates new form InfoAbeja
     */
    Abeja a; 
    public InfoAbeja(Abeja abeja) {
        a = abeja; 
        initComponents();
        if(abeja.getAncestros() == null){
            bTAncestro1.setEnabled(false);
            bTAncestro2.setEnabled(false);
        }
        id.setText(abeja.getId());
        pts.setText(Float.toString(abeja.getPuntaje())); 
        String color = "n";
        switch(abeja.getColorFav()){
                case 0:
                    color = "Rojo";
                    break;
                case 1:
                    color = "Verde";
                    break;
                case 2:
                    color = "Azul";
                    break;
                case 3:
                    color = "Amarillo";
                    break;
                case 4:
                    color = "Morado";
                    break;
                case 5:
                    color = "Celeste";
                    break;
                case 6:
                    color = "Naranja";
                    break;
                case 7:
                    color = "Rosa";
                    break;
            }
        colorFav.setText(color);
        String orden = "";
        switch (abeja.getOrden()){
            case 0:
                orden = "profundidad";
            case 1:
                orden = "Anchura";
            case 2:
                orden = "Random";
        }
        OrdBusq.setText(orden);
        dirFav.setText(abeja.getDireccionFav().name());
        distMax.setText(Integer.toString(abeja.getDistMax()));
        gen.setText(Integer.toString(abeja.getGeneracion()));
        adn.setText(abeja.getADN());
        System.out.println(abeja.getADN());
        isMutada.setState(abeja.isMutada());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bTAncestro1 = new javax.swing.JButton();
        bTAncestro2 = new javax.swing.JButton();
        colorFav = new javax.swing.JTextField();
        dirFav = new javax.swing.JTextField();
        OrdBusq = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        distMax = new javax.swing.JTextField();
        adn = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isMutada = new java.awt.Checkbox();
        pts = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Abeja");

        jLabel2.setText("Color Favorito");

        jLabel3.setText("Dirección Favorita");

        jLabel4.setText("Orden de busqueda");

        jLabel5.setText("Generación");

        jLabel6.setText("DistanciaMáxima");

        jLabel7.setText("Secuencia ADN");

        bTAncestro1.setText("Ancestro 1");
        bTAncestro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTAncestro1ActionPerformed(evt);
            }
        });

        bTAncestro2.setText("Ancestro 2");
        bTAncestro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTAncestro2ActionPerformed(evt);
            }
        });

        colorFav.setEditable(false);
        colorFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorFavActionPerformed(evt);
            }
        });

        dirFav.setEditable(false);

        OrdBusq.setEditable(false);

        gen.setEditable(false);
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });

        distMax.setEditable(false);

        adn.setEditable(false);

        id.setText("jLabel8");

        jLabel8.setText("Mutada");

        isMutada.setEnabled(false);

        pts.setText("jTextField1");
        pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptsActionPerformed(evt);
            }
        });

        jLabel9.setText("Puntos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(id)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(colorFav, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(dirFav)
                            .addComponent(OrdBusq))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)
                                .addComponent(isMutada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(distMax, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(gen))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(bTAncestro1)
                        .addGap(53, 53, 53)
                        .addComponent(bTAncestro2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(54, 54, 54)
                .addComponent(adn, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isMutada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(colorFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dirFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(OrdBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(distMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(adn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTAncestro1)
                    .addComponent(bTAncestro2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTAncestro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTAncestro1ActionPerformed
        new InfoAbeja(a.getAncestros()[0]).setVisible(true);
    }//GEN-LAST:event_bTAncestro1ActionPerformed

    private void colorFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFavActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void bTAncestro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTAncestro2ActionPerformed
        new InfoAbeja(a.getAncestros()[1]).setVisible(true);

    }//GEN-LAST:event_bTAncestro2ActionPerformed

    private void ptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptsActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrdBusq;
    private javax.swing.JTextField adn;
    private javax.swing.JButton bTAncestro1;
    private javax.swing.JButton bTAncestro2;
    private javax.swing.JTextField colorFav;
    private javax.swing.JTextField dirFav;
    private javax.swing.JTextField distMax;
    private javax.swing.JTextField gen;
    private javax.swing.JLabel id;
    private java.awt.Checkbox isMutada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pts;
    // End of variables declaration//GEN-END:variables
}
